dataset: all_fisheye

model_config:
  model_name: vprmodel
  feature_extractor:
    model: hloc_vgg16  # Choices: rps, vgg16, resnet18, hloc_vgg16
    fine_tuning: false

  clustering:
    model: hloc_netvlad # Choices: hloc_netvlad, netvlad
    num_clusters: 64
    desc_dim: 512
    normalize_input: true
    whiten: true
    alpha: 100.0

loss:
  name: hardtripletloss
  margin: 0.1
  hardest: false
  squared: false

training_epoch: 100
eval_config: {}
enable_tensorboard: true