dataset: isaac_office_all_fisheye

model_config:
  model_name: vprmodel
  feature_extractor:
    model: resnet18  # Choices: rps, vgg16, resnet18
    fine_tuning: false

  clustering:
    model: netvlad
    num_clusters: 64
    desc_dim: 512
    normalize_input: true
    whiten: true
    alpha: 100.0

loss:
  name: hardtripletloss
  margin: 0.1
  hardest: false
  squared: false

training_epoch: 100
eval_config: {}
enable_tensorboard: true